export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 100],
    'subject-case': [0],
    'subject-empty': [2, 'never'],
    'type-empty': [2, 'never'],
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'wip',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'app',
        'components',
        'mesh',
        'shaders',
        'utils',
        'lib',
        'styles',
        'config',
        'deps',
        'hooks',
        'api',
        'ui',
      ],
    ],
    'scope-case': [2, 'always', 'lower-case'],
  },
};
